[package]
name = "PESMario"
version = "0.1.0"
edition = "2023"
author = "Vijay J"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.0.1"
piston_window = "0.129.0"
